config/routes.rb
Product::Application.routes.draw do
  get 'home'=> 'users#home', as: 'home'

  get 'game/autocomplete' => 'game#autocomplete', as: 'game_autocomplete'
  post 'game/check' => 'game#check', as: 'game_check'
  get 'game/leaderboard' => 'game#leaderboard', as: 'game_leaderboard'
  get 'game/next' => 'game#next', as: 'game_next'
  get 'game/state' => 'game#state', as: 'game_state'
  get 'game/finish' => 'game#finish', as: 'game_finish'

  get 'open_id/accept' => 'open_id#accept', as: 'open_id_accept'
  get 'open_id/connect' => 'open_id#connect', as: 'open_id_connect'

  root :to => 'site#home'

end

app/models/user.rb
require File.join UserAuthentication::Engine.config.root, 'app/models/user.rb'

class User < ActiveRecord::Base
  #validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/game_controller.rb
require 'lib/people'
require 'lib/play'

class GameController < ApplicationController
  include GameHelper

  before_filter do |c|
    params[:action] == 'leaderboard' ? true : c.send(:authorize, root_path)
  end

  def autocomplete
    people = People.all

    pattern = params[:term].split.join('.*').downcase
    render json: people.map(&:name).select { |name| name.downcase =~ /.*#{pattern}.*/ }
  end

  def check
    if get_rounds < $globals.game.rounds
      set_result session[:name], params[:guess]
    end

    session[:state] = 'flipped'

    render json: {
        state: session[:state],
        score: session[:score] || 0,
        hit: session[:hit],
        name: session[:name],
        email: session[:email],
        image: session[:image],
        guess: session[:guess],
        remaining: $globals.game.rounds - (session[:rounds] || 0)
    }
  end

  def next
    if get_rounds < $globals.game.rounds
      if session[:state] == 'waiting' # This is a skip
        increase_round
      end

      set_current_round(People.all.sample)

      render json: {
          state: session[:state],
          score: session[:score] || 0,
          hit: session[:hit],
          image: session[:image],
          guess: session[:guess],
          remaining: $globals.game.rounds - (session[:rounds] || 0)
      }
    else
      # Run out of rounds to play.
      render json: {
          state: 'over',
          score: session[:score] || 0,
          hit: session[:hit],
          name: session[:name],
          email: session[:email],
          image: session[:image],
          guess: session[:guess],
          remaining: 0
      }
    end
  end

  def finish
    Play.finish(current_user, get_score)
    redirect_to game_leaderboard_path
  end

  def state
    render json: {
        state: session[:state],
        score: session[:score] || 0,
        hit: session[:hit],
        name: session[:name],
        image: session[:image],
        email: session[:email],
        guess: session[:guess],
        remaining: $globals.game.rounds - (session[:rounds] || 0)
    }
  end

  def leaderboard
    @leaderboard = Play.leaderboard
  end
end

app/controllers/open_id_controller.rb
class OpenIdController < ApplicationController
  include GameHelper

  skip_before_filter :authorize

  def connect
    response.headers['WWW-Authenticate'] = Rack::OpenID.build_header(
        identifier: 'https://www.appdirect.com/openid/id',
        required: ['email', 'fullname'],
        return_to: open_id_accept_url,
        realm: open_id_accept_url,
        method: 'GET')
    head 401
  end

  def accept
    response = request.env[Rack::OpenID::RESPONSE]
    redirect_to root_path unless response.present?

    case response.status
      when :success
        data = OpenID::SReg::Response.from_success_response(response)
        user = User.where(email: data['email']).first_or_initialize
        if data['fullname']
          user.name = data['fullname']
        end
        user.save!
        session[:user_id] = user.id

        reset_game
        redirect_to(session[:redirect_to] || home_path)
      when :failure
        flash[:error] = 'OpenId login failed.'
        redirect_to root_path
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    if current_user
      redirect_to home_path
    end
  end
end

app/controllers/users_controller.rb
require 'lib/people'

class UsersController < ApplicationController
  include GameHelper
  before_filter { |c| c.send :authorize, root_path }

  def home
    if session[:state]
      @person = People.find(session[:person_id])
    else
      @person = People.all.sample
      set_current_round(@person)
    end

    @score = get_score
    @rounds = $globals.game.rounds
    @remaining = $globals.game.rounds - get_rounds
  end

  def on_login
    reset_game
    redirect_to home_path
  end

  def on_logout
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_css(*sources)
    content_for(:css, sources.join(",") + ",")
  end

  def set_javascript(*sources)
    content_for(:javascript, sources.join(",") + ",")
  end

  def page_css
    if content_for?(:css)
      sources = content_for(:css).chomp(",").split(",")
      stylesheet_link_tag *sources
    end
  end

  def page_javascript
    if content_for?(:javascript)
      sources = content_for(:javascript).chomp(",").split(",")
      javascript_include_tag *sources
    end
  end
end

app/helpers/game_helper.rb
module GameHelper
  def get_score
    session[:score] ||= 0
  end

  def get_rounds
    session[:rounds] ||= 0
  end

  def set_current_round(person)
    session[:person_id] = person.id
    session[:name] = person.name
    session[:email] = person.email
    session[:image] = person.image
    session[:state] = 'waiting'
  end

  def reset_game
    session.delete :score
    session.delete :hit
    session.delete :rounds
    session.delete :name
    session.delete :guess
    session.delete :email
    session.delete :hit
    session.delete :image
    session.delete :person_id
    session.delete :state
  end

  def set_result(name, guess)
    hit = name.downcase == guess.downcase
    increase_score if hit
    increase_round

    session[:guess] = guess
    session[:hit] = hit
  end

  def increase_score
    session[:score] ||= 0
    session[:score] = session[:score] + 1
  end

  def increase_round
    session[:rounds] ||= 0
    session[:rounds] = session[:rounds] + 1
  end
end

app/views/game/leaderboard.html.haml
- set_css 'game/leaderboard'

%h3 Leaderboard

%ul.leaderboard
    - @leaderboard.each do |record|
        %li
            %span.leaderboard--name
                = record.user.name
            %span.leaderboard--score
                = record.score

app/views/layouts/_footer.html.haml
%footer
    - if current_user
        = link_to 'Logout', logout_path

app/views/layouts/_header.html.haml
%header
    %h1
        - if current_user
            = link_to home_path do
                Name that
                %span Coworker
        - else
            = link_to root_path do
                Name that
                %span Coworker

app/views/layouts/application.html.haml
- content_for :content do
    = render partial: 'layouts/header'
    - flash.each do |name, message|
        %div{class: "#{name}"}
            = message

    #main.clearfix{ :role => "main" }
        = yield

    = render partial: 'layouts/footer'

= render template: 'layouts/base'

app/views/layouts/base.html.haml
!!!DOCTYPE html
%html
    %head
        %meta{ :charset => "utf-8" }

        %title
            = content_for?(:title) ? "#{yield(:title)} • #{$globals.app.titlecase}" : $globals.app.titlecase
        %meta{ :name => "description", :content => "" }
        %meta{ :name => "author", :content => "" }

        %meta{ :name => "HandheldFriendly", :content => "True" }
        %meta{ :name => "MobileOptimized", :content => "320" }
        %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
        %meta{ "http-equiv" => "cleartype", :content => "on" }

        = stylesheet_link_tag 'application', :media => 'all'
        = page_css
        = csrf_meta_tags

    %body{ name: "#{controller.controller_name}/#{controller.action_name}", id: "#{controller.action_name}" }
        .background_1
        .background_2
        .background_3
        .background_4
        .background_5
        #container
            = content_for?(:content) ? yield(:content) : yield

        = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"
        :javascript
            window.jQuery || document.write('<script src="js/libs/jquery-1.6.2.min.js"><\/script>')

        = javascript_include_tag "//use.typekit.net/pmi5vzb.js"
        :javascript
            try{Typekit.load();}catch(e){}
        = javascript_include_tag 'application' # Includes jQuery. Must precede all other jQuery imports.
        = page_javascript

app/views/site/home.html.haml
-# - set_css 'site/home'

= form_tag open_id_connect_path, method: 'GET' do
    %menu
        %button{ :type => "submit" } Log in with AppDirect

app/views/users/home.html.haml
- set_css 'game/play'
- set_javascript 'game/play'

= form_tag game_check_path, :class => "game flip", :data => {"next" => game_next_path, "finish" => game_finish_path, "state" => game_state_path} do
    .flipper{class: @remaining == 0 ? "flipped" : ""}
        .face.front
            .card.card__initial.clearfix
                .card--image
                    = image_tag @person.image
                %fieldset.card--content
                    .field
                        = search_field_tag 'guess', '', :placeholder => "e.g., Johnny Apple"
                %menu.form--submit
                    = button_tag 'Enter', :type => "submit", :id => "button_enter"
                    = button_tag 'Skip', :type => "button", :id => "button_skip"
        .face.back
            .card.card__result
                .card--content
                    %span.status.status__correct
                        %i.icon__smile_big
                        Correct!
                    %span.status.status__incorrect
                        %span.guess
                        %i.icon__frown
                        Wrong
                    %h2.name
                        Test name
                    %p
                        Title
                        %br
                        Department
                        %br
                        Location
                    %p
                        Say hey
                        %br
                        %a.email{ :href => "mailto:email@address.com" }
                            email@address.com
                %menu.form--submit
                    = button_tag 'Next', :type => "submit", :id => "button_next"
                %menu.finish
                    = button_tag 'Finish', id: 'button_finish'
.score
    .score--unit.score--unit__correct
        %span.score--number< #{@score}
        %span.score--text correct
    .score--unit.score--unit__total
        %span.score--number>< #{@rounds}
        %span.score--text total
    .score--unit.score--unit__rounds
        %span.score--number< #{@remaining}
        %span.score--text more tries